export const exampleJobOffer = {
  id: '1',
  position: 'Programmer',
  client: 'example client',
  vacancies: 1,
  requestCreationDate: 1624135607,
  jobOfferCreationDate: 1624654007,
  closeJobOfferDate: 1626827707,
  closeMessage: '',
  sla_start: 1624826807,
  sla_end: 1626727607,
  contractType: [-1],
  recruiter: 'example recruiter',
  shiftType: 'PART_TIME',
  maxSalary: 10000,
  yearsExperience: 2,
  levelOfStudies: 'TECHNICAL',
  formationStatus: 'TITLED',
  languages: [{ language: 'Ingles', level: 'medio', type: 'WRITING' }],
  softSkills: ['skill 1'],
  requiresComputer: true,
  offerDescription: 'description',
  questions: ['question 1', 'question 2'],
  serviceType: 'INTERNAL',
  specialRequirements: ['requirement 1'],
  technicalRequirements: [{ requirement: 'example', obligatoriness: 'EXCLUDING' }],
  workAddress: {
    city: 'Santiago',
    number: '123',
    comuna: 'Santiago',
    country: 'Chile',
    street: 'Calle',
  },
  messages: [],
};

export const exampleRequest = {
  id: '1',
  client: 'example client',
  contractType: [-1],
  requestCreationDate: 1624135607,
  jobOfferCreationDate: 1624654007,
  closeJobOfferDate: 1626827707,
  closeMessage: '',
  sla_start: 1624826807,
  sla_end: 1626727607,
  position: 'Programmer',
  vacancies: 1,
  approxStartDate: '17/05/2021',
  possibleDuration: 2,
  requestDescription: '',
  recruiter: 'example recruiter',
  levelOfStudies: 'TECHNICAL',
  languages: [{ language: 'Ingles', level: 'medio', type: 'WRITING' }],
  maxSalary: 10000,
  formationStatus: 'TITLED',
  softSkills: ['skill 1'],
  serviceType: 'INTERNAL',
  yearsExperience: 2,
  shiftType: 'PART_TIME',
  requiresComputer: true,
  specialRequirements: ['requirement 1'],
  technicalRequirements: [{ requirement: 'example', obligatoriness: 'EXCLUDING' }],
  workAddress: {
    city: 'Santiago',
    number: '123',
    comuna: 'Santiago',
    country: 'Chile',
    street: 'Calle',
  },
};

export const emptyRequest = {
  id: '1',
  client: 'example client',
  contractType: [],
  requestCreationDate: 1624135607,
  jobOfferCreationDate: 1624654007,
  closeJobOfferDate: 1626827707,
  closeMessage: '',
  sla_start: 1624826807,
  sla_end: 1626727607,
  position: 'Programmer',
  vacancies: 1,
  approxStartDate: '',
  possibleDuration: 2,
  requestDescription: '',
  recruiter: 'example recruiter',
  levelOfStudies: '',
  languages: [],
  maxSalary: null,
  formationStatus: '',
  softSkills: [],
  serviceType: '',
  yearsExperience: null,
  shiftType: '',
  requiresComputer: null,
  specialRequirements: [],
  technicalRequirements: [],
  workAddress: null,
};
