export const NewRequests = [
  {
    id: '00001',
    name: 'Programador',
    vacancies: 3,
    job_duration: '3 meses',
    description_summary: 'Desarrollador Java, Python y Ruby',
    created_date: new Date('10/30/2019'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
  },
  {
    id: '00002',
    name: 'Administrador de sistemas raw',
    vacancies: 2,
    job_duration: '2 meses',
    description_summary: 'Lorem ipsum dolor sit amet.',
    created_date: new Date('11/30/2019'),
    job_description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi, natus nobis dolor vel quod quos vitae soluta modi odit quo.',
  },
  {
    id: '00003',
    name: 'Analista en programación',
    vacancies: 4,
    job_duration: '3 meses',
    description_summary: 'Lorem ipsum dolor sit amet consectetur.',
    created_date: new Date('01/30/2020'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
  },
  {
    id: '00004',
    name: 'Ingeniero en informática',
    vacancies: 1,
    job_duration: '1 mes',
    description_summary: 'Desarrollador Java, Python y Ruby',
    created_date: new Date('11/30/2020'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
  },
  {
    id: '00005',
    name: 'Ingeniero DevOps',
    vacancies: 6,
    job_duration: '2 meses',
    description_summary: 'Desarrollador Java, Python y Ruby',
    created_date: new Date('01/30/2021'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
  },
  {
    id: '00006',
    name: 'Data engineer',
    vacancies: 2,
    job_duration: '1 mes',
    description_summary: 'Desarrollador Java, Python y Ruby',
    created_date: new Date('02/30/2021'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
  },
  {
    id: '00007',
    name: 'Analista en programación',
    vacancies: 4,
    job_duration: '3 meses',
    description_summary: 'Lorem ipsum dolor sit amet consectetur.',
    created_date: new Date('01/30/2020'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
  },
  {
    id: '00008',
    name: 'Ingeniero en informática',
    vacancies: 1,
    job_duration: '1 mes',
    description_summary: 'Desarrollador Java, Python y Ruby',
    created_date: new Date('11/30/2020'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
  },
  {
    id: '00009',
    name: 'Ingeniero DevOps',
    vacancies: 6,
    job_duration: '2 meses',
    description_summary: 'Desarrollador Java, Python y Ruby',
    created_date: new Date('01/30/2021'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
  },
  {
    id: '00010',
    name: 'Data engineer',
    vacancies: 2,
    job_duration: '1 mes',
    description_summary: 'Desarrollador Java, Python y Ruby',
    created_date: new Date('02/30/2021'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
  },

];

export const PostedRequests = [
  {
    id: '10001',
    status: 'start',
    name: 'Desarrollador',
    vacancies: 3,
    job_duration: '3 meses',
    description_summary: 'Desarrollador Java, Python y Ruby',
    created_date: new Date('05/30/2020'),
    posted_date: new Date('10/30/2020'),
    SLA: new Date('10/30/2021'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
    first_stage: [12346, 12345, 12344],
    second_stage: [12343, 12342],
    third_stage: [12321],
    fourth_stage: [12322, 12323],
  },
  {
    id: '10002',
    status: 'on-going',
    name: 'Administrador de sistemas war',
    vacancies: 2,
    job_duration: '2 meses',
    description_summary: 'Lorem ipsum dolor sit amet.',
    created_date: new Date('10/30/2020'),
    posted_date: new Date('11/30/2020'),
    SLA: new Date('05/22/2021'),
    job_description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi, natus nobis dolor vel quod quos vitae soluta modi odit quo.',
    first_stage: [12346, 12345, 12344],
    second_stage: [12343, 12342],
    third_stage: [12341],
    fourth_stage: [12322, 12323],
  },
  {
    id: '10003',
    status: 'ready',
    name: 'Analista',
    vacancies: 4,
    job_duration: '3 meses',
    description_summary: 'Lorem ipsum dolor sit amet consectetur.',
    created_date: new Date('01/25/2020'),
    posted_date: new Date('01/30/2020'),
    SLA: new Date('05/23/2021'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
    first_stage: [12346, 12345, 12344],
    second_stage: [12343, 12342],
    third_stage: [12341],
    fourth_stage: [12322, 12323],
  },
  {
    id: '10004',
    status: 'start',
    name: 'Ingeniero en Datos',
    vacancies: 1,
    job_duration: '1 mes',
    description_summary: 'Desarrollador Java, Python y Ruby',
    created_date: new Date('11/30/2020'),
    posted_date: new Date('11/15/2020'),
    SLA: new Date('05/10/2021'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
    first_stage: [12346, 12345, 12344],
    second_stage: [12343, 12342],
    third_stage: [12321],
    fourth_stage: [12322, 12323],
  },
  {
    id: '10005',
    status: 'ready',
    name: 'Data Scientist',
    vacancies: 6,
    job_duration: '2 meses',
    description_summary: 'Desarrollador Java, Python y Ruby',
    created_date: new Date('11/30/2020'),
    posted_date: new Date('01/10/2021'),
    SLA: new Date('05/30/2021'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
    first_stage: [12325, 12345, 12344],
    second_stage: [12343, 12342],
    third_stage: [12321],
    fourth_stage: [12324, 12323],
  },
  {
    id: '10006',
    status: 'on-going',
    name: 'BI Engineer',
    vacancies: 2,
    job_duration: '1 mes',
    description_summary: 'Desarrollador Java, Python y Ruby',
    created_date: new Date('01/30/2020'),
    posted_date: new Date('02/15/2021'),
    SLA: new Date('05/25/2021'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
    first_stage: [12346, 12345, 12344],
    second_stage: [12343, 12342],
    third_stage: [12321],
    fourth_stage: [12322, 12323],
  },
  {
    id: '10007',
    status: 'ready',
    name: 'Analista',
    vacancies: 4,
    job_duration: '3 meses',
    description_summary: 'Lorem ipsum dolor sit amet consectetur.',
    created_date: new Date('01/25/2020'),
    posted_date: new Date('01/30/2020'),
    SLA: new Date('05/23/2021'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
    first_stage: [12346, 12345, 12344],
    second_stage: [12343, 12342],
    third_stage: [12341],
    fourth_stage: [12322, 12324],
  },
  {
    id: '10008',
    status: 'start',
    name: 'Ingeniero en Datos',
    vacancies: 1,
    job_duration: '1 mes',
    description_summary: 'Desarrollador Java, Python y Ruby',
    created_date: new Date('11/30/2020'),
    posted_date: new Date('11/15/2020'),
    SLA: new Date('05/10/2021'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
    first_stage: [12322, 12345, 12344],
    second_stage: [12343, 12325],
    third_stage: [12321],
    fourth_stage: [12324, 12323],
  },
  {
    id: '10009',
    status: 'ready',
    name: 'Data Scientist',
    vacancies: 6,
    job_duration: '2 meses',
    description_summary: 'Desarrollador Java, Python y Ruby',
    created_date: new Date('11/30/2020'),
    posted_date: new Date('01/10/2021'),
    SLA: new Date('05/30/2021'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
    first_stage: [12346, 12345, 12344],
    second_stage: [12325, 12342],
    third_stage: [12321],
    fourth_stage: [12322, 12323],
  },
  {
    id: '10010',
    status: 'on-going',
    name: 'BI Engineer',
    vacancies: 2,
    job_duration: '1 mes',
    description_summary: 'Desarrollador Java, Python y Ruby',
    created_date: new Date('01/30/2020'),
    posted_date: new Date('02/15/2021'),
    SLA: new Date('05/25/2021'),
    job_description: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
    first_stage: [12325, 12345, 12344],
    second_stage: [12343, 12342],
    third_stage: [12321],
    fourth_stage: [12322, 12323],
  },

];
