export interface CreateRequestType {
  approxStartDate: Date,
  client: string,
  contractType: string,
  formationStatus: string,
  internalRep:string,
  levelOfStudies: string,
  languages: { language: string, level: string }[],
  maxSalary: number,
  position: string,
  possibleDuration: number,
  recruiter: string,
  requestDescription: string,
  requiresComputer: boolean,
  serviceType: string,
  shiftType: string,
  softSkills: Array<string>,
  specialRequirements: Array<string>,
  stage: string,
  technicalRequirements: Array<string>,
  vacancies: number,
  workAdress: string,
  yearsExperience: number,
  [key: string]: string | Date | boolean | Array<string> |
  Array<string> | { language: string, level: string }[] | Array<string> | number
}
