export interface CreateRequestTypeString {
  approxStartDate: Date,
  client: string,
  contractType: string,
  formationStatus: string,
  internalRep:string,
  levelOfStudies: string,
  languages: { id: string; label: string; language: string; level: string; }[],
  maxSalary: string,
  position: string,
  possibleDuration: string,
  recruiter: string,
  requestDescription: string,
  requiresComputer: string,
  serviceType: string,
  shiftType: string,
  softSkills: string,
  specialRequirements: string,
  stage: string,
  technicalRequirements: string,
  vacancies: string,
  workAdress: string,
  yearsExperience: string,
  [key: string]:string | Date | { id: string; label: string; language: string; level: string; }[]
}
